export interface TourStep {
  target: string | null; // data-tour value, or null for a centered welcome/finish card
  page?: string; // route to navigate to before this step (omit to stay on current page)
  title: string;
  description: string;
  placement?: "top" | "bottom" | "left" | "right";
}

export type TourLanguage = "en" | "hi";

export const TOUR_STEPS_EN: TourStep[] = [
  {
    target: null,
    page: "/dashboard",
    title: "Welcome to Billing ERP! \u{1F44B}",
    description:
      "Let's walk through every major section — Sales, Purchase, Inventory, CRM, HR, Manufacturing, Reports, and Settings. Click 'End Tour' anytime to skip.",
  },
  {
    target: "nav-dashboard",
    page: "/dashboard",
    title: "Dashboard",
    description: "See today's sales, purchases, due payments, and low-stock products at a glance here.",
    placement: "right",
  },
  {
    target: "dashboard-kpis",
    page: "/dashboard",
    title: "Today's Numbers",
    description: "Today's sales, purchases, receivables, and payables — all in one place.",
    placement: "top",
  },
  {
    target: "dashboard-quick-actions",
    page: "/dashboard",
    title: "Quick Actions",
    description: "Start a new invoice, product, customer, purchase, or expense with one click from anywhere.",
    placement: "bottom",
  },
  {
    target: "header-search",
    page: "/dashboard",
    title: "Quick Search",
    description: "Quickly search for any product, customer, or invoice here.",
    placement: "bottom",
  },
  {
    target: "header-profile",
    page: "/dashboard",
    title: "Your Profile",
    description: "Log out, or view and update your profile (including your password) here.",
    placement: "bottom",
  },
  {
    target: "nav-sales",
    page: "/sales/new",
    title: "Sales — New Invoice",
    description: "This is where you create a bill. Let's look at how it works.",
    placement: "right",
  },
  {
    target: "tour-customer-picker",
    page: "/sales/new",
    title: "Pick a Customer",
    description: "Search an existing customer, add a new one on the fly, or leave it blank for a walk-in sale.",
    placement: "bottom",
  },
  {
    target: "tour-product-search",
    page: "/sales/new",
    title: "Add Products",
    description: "Search by name, SKU, or barcode to add items — quantity, price, discount, and GST are all editable per line.",
    placement: "bottom",
  },
  {
    target: "tour-payment-section",
    page: "/sales/new",
    title: "Payment",
    description: "Take a single payment method, split across several, or leave it fully on credit — due amount is tracked automatically.",
    placement: "top",
  },
  {
    target: "tour-sales-history",
    page: "/sales/invoices",
    title: "Sales History",
    description: "Every invoice you've created — view, print, or download any of them as a PDF from here.",
    placement: "top",
  },
  {
    target: "nav-purchase",
    page: "/purchase/new",
    title: "Purchase",
    description: "Record what you buy from suppliers here — stock increases automatically when you save.",
    placement: "right",
  },
  {
    target: "tour-supplier-picker",
    page: "/purchase/new",
    title: "Pick a Supplier",
    description: "Same idea as customers — search, add new, then add the products you're purchasing below.",
    placement: "bottom",
  },
  {
    target: "nav-products",
    page: "/products",
    title: "Products",
    description: "Every product you sell or stock lives here, with stock levels shown live.",
    placement: "right",
  },
  {
    target: "tour-add-product",
    page: "/products",
    title: "Add a Product",
    description: "Set purchase price, selling price, GST rate, and opening stock — plus manage Categories and Units from here too.",
    placement: "bottom",
  },
  {
    target: "nav-inventory",
    page: "/inventory/stock",
    title: "Inventory",
    description: "Current stock, stock adjustments, full stock history, and low-stock alerts — all under this menu.",
    placement: "right",
  },
  {
    target: "tour-customers",
    page: "/customers",
    title: "Customers",
    description: "Manage customer details, and open any customer's ledger to see their full payment history.",
    placement: "top",
  },
  {
    target: "tour-suppliers",
    page: "/suppliers",
    title: "Suppliers",
    description: "Same as customers, but for the people you buy from — with their own ledger too.",
    placement: "top",
  },
  {
    target: "tour-crm",
    page: "/crm/leads",
    title: "CRM — Leads",
    description: "Track potential customers, log follow-ups, and move them through your sales pipeline (New → Won/Lost).",
    placement: "top",
  },
  {
    target: "tour-hr",
    page: "/hr/employees",
    title: "HR & Payroll",
    description: "Manage employees, mark daily attendance, and run monthly payroll — all from the HR menu.",
    placement: "top",
  },
  {
    target: "tour-manufacturing",
    page: "/manufacturing/bom",
    title: "Manufacturing",
    description: "Define what a finished product is made of (Bill of Materials), then create Production Orders that consume raw stock automatically.",
    placement: "top",
  },
  {
    target: "tour-expenses",
    page: "/expenses",
    title: "Expenses",
    description: "Log business expenses like rent, salary, or utilities — categorized and ready for reporting.",
    placement: "top",
  },
  {
    target: "tour-payments",
    page: "/payments",
    title: "Payments",
    description: "Receive a payment against a customer's due invoice, or pay off a supplier's due purchase.",
    placement: "top",
  },
  {
    target: "nav-reports",
    page: "/reports/sales",
    title: "Reports",
    description: "Sales, Purchase, Profit, Stock, GST, and more — every report can be filtered by date and exported as Excel or PDF.",
    placement: "right",
  },
  {
    target: "tour-users",
    page: "/users",
    title: "Users & Roles",
    description: "Add team members and control exactly what each role can see and do, right down to the module and action.",
    placement: "top",
  },
  {
    target: "tour-settings",
    page: "/settings/business",
    title: "Settings",
    description: "Your business profile, invoice settings, number series, data import, and backup all live here.",
    placement: "top",
  },
  {
    target: null,
    title: "You're all set! \u{1F389}",
    description: "Click the help (?) icon in the header anytime to see this tour again.",
  },
];

export const TOUR_STEPS_HI: TourStep[] = [
  {
    target: null,
    page: "/dashboard",
    title: "बिलिंग ईआरपी में आपका स्वागत है! \u{1F44B}",
    description:
      "चलिए हर बड़े हिस्से को देखते हैं — सेल्स, परचेज़, इन्वेंटरी, सीआरएम, एचआर, मैन्युफैक्चरिंग, रिपोर्ट्स और सेटिंग्स। कभी भी 'टूर खत्म करें' दबाकर बाहर आ सकते हैं।",
  },
  {
    target: "nav-dashboard",
    page: "/dashboard",
    title: "डैशबोर्ड",
    description: "यहां आज की सेल्स, परचेज़, बकाया पेमेंट्स और कम स्टॉक वाले प्रोडक्ट्स एक नज़र में दिखते हैं।",
    placement: "right",
  },
  {
    target: "dashboard-kpis",
    page: "/dashboard",
    title: "आज के आंकड़े",
    description: "आज की सेल्स, परचेज़, प्राप्य और देय राशि — सब यहां एक नज़र में।",
    placement: "top",
  },
  {
    target: "dashboard-quick-actions",
    page: "/dashboard",
    title: "क्विक एक्शन्स",
    description: "नया इनवॉइस, प्रोडक्ट, कस्टमर, परचेज़ या खर्च — एक क्लिक में कहीं से भी शुरू करें।",
    placement: "bottom",
  },
  {
    target: "header-search",
    page: "/dashboard",
    title: "क्विक सर्च",
    description: "किसी भी प्रोडक्ट, कस्टमर या इनवॉइस को तुरंत ढूंढने के लिए यहां सर्च करें।",
    placement: "bottom",
  },
  {
    target: "header-profile",
    page: "/dashboard",
    title: "आपकी प्रोफाइल",
    description: "यहां से लॉगआउट करें, या अपनी प्रोफाइल (पासवर्ड सहित) देखें और बदलें।",
    placement: "bottom",
  },
  {
    target: "nav-sales",
    page: "/sales/new",
    title: "सेल्स — नया इनवॉइस",
    description: "यहीं से बिल बनता है। चलिए देखते हैं ये कैसे काम करता है।",
    placement: "right",
  },
  {
    target: "tour-customer-picker",
    page: "/sales/new",
    title: "कस्टमर चुनें",
    description: "पुराना कस्टमर सर्च करें, नया add करें, या walk-in sale के लिए खाली छोड़ दें।",
    placement: "bottom",
  },
  {
    target: "tour-product-search",
    page: "/sales/new",
    title: "प्रोडक्ट्स जोड़ें",
    description: "नाम, SKU या बारकोड से सर्च करके प्रोडक्ट जोड़ें — क्वांटिटी, प्राइस, डिस्काउंट और GST हर लाइन में बदल सकते हैं।",
    placement: "bottom",
  },
  {
    target: "tour-payment-section",
    page: "/sales/new",
    title: "पेमेंट",
    description: "एक पेमेंट method चुनें, कई में बांटें, या पूरी credit पर छोड़ दें — due amount अपने आप track होता है।",
    placement: "top",
  },
  {
    target: "tour-sales-history",
    page: "/sales/invoices",
    title: "सेल्स हिस्ट्री",
    description: "अब तक बनाए गए सभी इनवॉइस — यहां से देखें, प्रिंट करें, या PDF डाउनलोड करें।",
    placement: "top",
  },
  {
    target: "nav-purchase",
    page: "/purchase/new",
    title: "परचेज़",
    description: "सप्लायर से सामान खरीदने की एंट्री यहां होती है — सेव करते ही स्टॉक अपने आप बढ़ जाता है।",
    placement: "right",
  },
  {
    target: "tour-supplier-picker",
    page: "/purchase/new",
    title: "सप्लायर चुनें",
    description: "कस्टमर जैसा ही तरीका — सर्च करें, नया जोड़ें, फिर नीचे खरीदे जा रहे प्रोडक्ट्स जोड़ें।",
    placement: "bottom",
  },
  {
    target: "nav-products",
    page: "/products",
    title: "प्रोडक्ट्स",
    description: "आपके सभी प्रोडक्ट्स यहां हैं, स्टॉक लेवल live दिखता है।",
    placement: "right",
  },
  {
    target: "tour-add-product",
    page: "/products",
    title: "प्रोडक्ट जोड़ें",
    description: "purchase price, selling price, GST rate और opening stock सेट करें — साथ ही Categories और Units भी यहीं से मैनेज करें।",
    placement: "bottom",
  },
  {
    target: "nav-inventory",
    page: "/inventory/stock",
    title: "इन्वेंटरी",
    description: "करंट स्टॉक, स्टॉक एडजस्टमेंट, पूरी स्टॉक हिस्ट्री और लो-स्टॉक अलर्ट — सब इसी मेन्यू में।",
    placement: "right",
  },
  {
    target: "tour-customers",
    page: "/customers",
    title: "कस्टमर्स",
    description: "कस्टमर डिटेल्स मैनेज करें, और किसी भी कस्टमर की ledger खोलकर पूरी पेमेंट हिस्ट्री देखें।",
    placement: "top",
  },
  {
    target: "tour-suppliers",
    page: "/suppliers",
    title: "सप्लायर्स",
    description: "कस्टमर जैसा ही, लेकिन उन लोगों के लिए जिनसे आप खरीदते हैं — इनकी भी अपनी ledger होती है।",
    placement: "top",
  },
  {
    target: "tour-crm",
    page: "/crm/leads",
    title: "सीआरएम — लीड्स",
    description: "संभावित ग्राहकों को track करें, follow-up नोट करें, और उन्हें pipeline में आगे बढ़ाएं (New → Won/Lost)।",
    placement: "top",
  },
  {
    target: "tour-hr",
    page: "/hr/employees",
    title: "एचआर एंड पेरोल",
    description: "एम्प्लॉई मैनेज करें, रोज़ की attendance mark करें, और महीने की payroll यहीं से run करें।",
    placement: "top",
  },
  {
    target: "tour-manufacturing",
    page: "/manufacturing/bom",
    title: "मैन्युफैक्चरिंग",
    description: "तय करें कि finished product किन components से बनता है (BOM), फिर Production Order बनाएं जो raw material अपने आप consume कर ले।",
    placement: "top",
  },
  {
    target: "tour-expenses",
    page: "/expenses",
    title: "खर्च (Expenses)",
    description: "रेंट, सैलरी, बिजली जैसे खर्च यहां दर्ज करें — category के हिसाब से, reporting के लिए तैयार।",
    placement: "top",
  },
  {
    target: "tour-payments",
    page: "/payments",
    title: "पेमेंट्स",
    description: "कस्टमर के बकाया इनवॉइस के खिलाफ पेमेंट लें, या सप्लायर के बकाया purchase का भुगतान करें।",
    placement: "top",
  },
  {
    target: "nav-reports",
    page: "/reports/sales",
    title: "रिपोर्ट्स",
    description: "सेल्स, परचेज़, प्रॉफिट, स्टॉक, जीएसटी और बहुत कुछ — हर रिपोर्ट को date से filter करें और Excel/PDF में export करें।",
    placement: "right",
  },
  {
    target: "tour-users",
    page: "/users",
    title: "यूज़र्स एंड रोल्स",
    description: "टीम मेंबर्स जोड़ें और कंट्रोल करें कि हर role module aur action level पर क्या देख/कर सकता है।",
    placement: "top",
  },
  {
    target: "tour-settings",
    page: "/settings/business",
    title: "सेटिंग्स",
    description: "आपकी business profile, invoice settings, number series, data import और backup — सब यहीं मिलेगा।",
    placement: "top",
  },
  {
    target: null,
    title: "बस हो गया! \u{1F389}",
    description: "इस टूर को दोबारा देखने के लिए कभी भी हेडर के हेल्प (?) आइकन पर क्लिक करें।",
  },
];

export function getTourSteps(language: TourLanguage): TourStep[] {
  return language === "hi" ? TOUR_STEPS_HI : TOUR_STEPS_EN;
}
